language: csharp

addons:
  apt:
    packages:
      - imagemagick

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      mono: none
      env: CONFIGURATION=Debug DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 2.0.0
      mono: none
      env: CONFIGURATION=Release DOTNETCORE=1

script:
  - dotnet restore
  - cd src/NMagickWand
  - dotnet build -c $CONFIGURATION
  - cd ../../test/NMagickWand.Tests
  - dotnet build -c $CONFIGURATION
#  - dotnet test -c $CONFIGURATION -f netcoreapp1.1
