namespace NMagickWand.Enums
{
    public enum MagickEvaluateOperator
    {
        UndefinedEvaluateOperator,
        AddEvaluateOperator,
        AndEvaluateOperator,
        DivideEvaluateOperator,
        LeftShiftEvaluateOperator,
        MaxEvaluateOperator,
        MinEvaluateOperator,
        MultiplyEvaluateOperator,
        OrEvaluateOperator,
        RightShiftEvaluateOperator,
        SetEvaluateOperator,
        SubtractEvaluateOperator,
        XorEvaluateOperator,
        PowEvaluateOperator,
        LogEvaluateOperator,
        ThresholdEvaluateOperator,
        ThresholdBlackEvaluateOperator,
        ThresholdWhiteEvaluateOperator,
        GaussianNoiseEvaluateOperator,
        ImpulseNoiseEvaluateOperator,
        LaplacianNoiseEvaluateOperator,
        MultiplicativeNoiseEvaluateOperator,
        PoissonNoiseEvaluateOperator,
        UniformNoiseEvaluateOperator,
        CosineEvaluateOperator,
        SineEvaluateOperator,
        AddModulusEvaluateOperator,
        MeanEvaluateOperator,
        AbsEvaluateOperator,
        ExponentialEvaluateOperator,
        MedianEvaluateOperator,
        SumEvaluateOperator,
        RootMeanSquareEvaluateOperator
    }
}
